---
- name: Print Firewall Rule Set
  hosts: palo
  connection: local
  gather_facts: False
  collections:
    - paloaltonetworks.panos
  tasks:

  # - name: Gather facts for device
  #   panos_facts:
  #     provider: '{{ pan_provider }}'

  # - name: Get the system info
  #   panos_op:
  #     provider: '{{ pan_provider }}'
  #     cmd: 'show system info'
  #   register: res

  # - debug:
  #     msg: '{{ res.stdout }}'

  - name: Get definition of Policy object (name wont be working!)
    panos_security_rule:
      provider: "{{ pan_provider }}"
      gathered_filter: 'description contains rule'
      state: gathered
    register: rule2
  - debug:
      msg: '{{ rule2 }}'

  - name: Fetch URL category (List of URLs)
    panos_custom_url_category:
      provider: "{{ pan_provider }}"
      name: 'DockerHub'
      state: gathered
    register: rule1
  - debug:
      msg: '{{ rule1 }}'